### ISSUE TITLE
Jison branch

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#10]
I did some investigation on recent issues opened on the repo.
After some digging on actual source code, my opinion is
that [pegjs](http://pegjs.org/) is not a good fit for the work.

@grncdr said us more than once, I think that the most important issue with pegjs 
is that it doesn't allow to use custom tokenizer.

So I spent some day giving a shot to [jison](http://zaa.ch/jison/) to see if it could be a better choice.

I started a new blank `jison` branch and start from scratch. 
I followed [POSIX shell specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html), so this doesn't 
exactly parse `bash` code... this could be a problem, or could be not, I don't know in details how @dthree plan to implement
cash, and I ask his opinion before going on...

# Status of implementation

I put this stuff together in some days, so expect lot of bug. 
I am anyway confident that the code has a good structure and we could procede at good pace.

There are 57 ava tests passing...

And here is a list of things that actually works or are still missing:

- [X] io redirection
- [X] pipes
- [X] quoting
- [X] &&, ||
- [X] simple commands
- [X] io redirection
- [X] subshell
- [X] for clause
- [X] case clause
- [X] if clause
- [X] while clause
- [X] function definition
- [X] var assignment
- [ ] Here-Document
- [ ] Arhitmetic substitutions
- [ ] Arguments substitution
- [ ] Command substitution
- [ ] Alias substitution

I ask you for some feedback on the idea... 
I will follow with a brief description of the structure of the code.

**Comment by parro-it** [comment]
* All sources are under folder `src`

* Main grammar file is grammar.jison. I copied the [grammar of the POSIX specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02) as-is, and then I add js code to generate AST

* the custom tokenizer is implemented as a set of iterator function composed together. The first one is in `token-delimiter.js`. This one receive a string with source as input and emit a set of tokens according  to [POSIX rules for token recognition](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03). The file is commented with the rules explanation.

* All other iterators are implemented in `tokenization-rules.js`. Each one implements one of the  [grammar rules of specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02)

* All iterators are composed together in a way acceptable by jison in file `posix-shell-lexer.js`

* ast-builder.js contains functions that actually generates AST. They are called from within the grammar. 

* And finally index.js require the generated js grammar, instantiate the tokenizer and add the ast-builder.

**Comment by parro-it** [comment]
I hope to have been at least understandable, I'm not a native english speaker...

**Comment by piranna** [comment]
> I followed POSIX shell specification, so this doesn't 
> exactly parse bash code... this could be a problem, or could be not

I'm ok with that, first implement support for POSIX shell and later we'll see about optionally adding `bash` extensions (but I'm not too much into it...).


> I ask you for some feedback on the idea...

As far as it's complete, it gives a clean AST and it's fast, it's good for me.


> I copied the grammar of the POSIX specification as-is

:+1: 


> I hope to have been at least understandable, I'm not a native english speaker...

Me too :-P What an awesome work, seems the architecture is really clear, congrats! Keep going on! :-D

**Comment by parro-it** [comment]
> As far as it's complete, 
Not at the moment, but it wil...

> it gives a clean AST 
I have some doubt on this. I try to name nodes as rules in grammar, but this get way too verbose... 
Look in tests source code at the AST produced when you'll have time, we should discuss for improvements...

> and it's fast, it's good for me.
It is pretty fast apparently, but this is relative to anyone expectations I guess.


> Me too :-P 
👍 

> What an awesome work, seems the architecture is really clear, congrats! 
Thank you!

> Keep going on! :-D
I will! Until now it has been really fun...

**Comment by piranna** [comment]
> I try to name nodes as rules in grammar

Good idea :-)


> I will! Until now it has been really fun...

That's the point after all ;-)
