### ISSUE TITLE
Implement substitutions

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#16]

**Comment by parro-it** [comment]
Command and parameters substitution are completed (except for callbacks).
Discussion on arithmetic substitution continue on #24

**Comment by piranna** [comment]
What's the problem with callbacks?

**Comment by parro-it** [comment]
We already discussed that problem: to produce a correct AST, the grammar should be able to callback into the shell to actually perform the command or parameter expansion.

The result of the expansion could possibly change the enclosing contest, producing a different grammar.

But we choose to implement callback in a future iteration of the module...

**Comment by piranna** [comment]
> We already discussed that problem: to produce a correct AST, the grammar
should be able to callback into the shell to actually perform the command
or parameter expansion.

You are right, I forgot that, sorry for my question.

> But we choose to implement callback in a future iteration of the module...

As I said then, it would be a matter of adding an optional callback on the
parser constructor. How much would cost to do it?

**Comment by parro-it** [comment]
> You are right, I forgot that, sorry for my question.

No problem :+1: 

> As I said then, it would be a matter of adding an optional callback on the
parser constructor. How much would cost to do it?

It should be relatively easy...
