### ISSUE TITLE
Weird behaviour running unit tests

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#2]
I got a strange behavior running unit tests on ` js-shell-pars`. 
If I run all tests file, I got two tests failure. But if I run them file by file, they all pass.
It appear some tests has unwanted side effect.
Did you notice the same thing? 
I will investigate it more, but maybe you have noticed the same thing and already find a solution?

**Comment by dthree** [comment]
I noticed that. Added you to the repo, if you want to pull down `js-shell-parse` and pop it up here, go ahead. Ensure you keep the git history though, as @grncdr's contributions should absolutely stay in it.

**Comment by grncdr** [comment]
It is (was) a bug in the tests, that is fixed upstream

**Comment by dthree** [comment]
Awesome thanks! :+1:

**Comment by parro-it** [comment]
Cool @grncdr! 
@dthree: ok, I will push the repo this evening...

**Comment by parro-it** [comment]
@grncdr I pulled upstream but I continue to get errors on tests. I notice you add `scripts/import-shellcheck-tests.shjs`. It's something I have to run before running tests?

**Comment by grncdr** [comment]
could you open an issue on js-shell-parse? it's expected that there are a bunch of errors, since there are a lot of fixtures for test cases that aren't yet covered by the parser. I can't tell if you're seeing something expected without knowing what error you are receiving.

**Comment by parro-it** [comment]
Thank you @grncdr, I skipped for now `shellcheck` tests and all tests passes now. Closing this issue, I will open another to track progress with these tests.
