### ISSUE TITLE
Implement assignements

### ISSUE THREAD

**Issue by piranna** [vorpaljs/bash-parser#20]
The spec says that it should return the `ASSIGNMENT_WORD` token, but I think it should return a expanded AST node.

**Comment by piranna** [comment]
Ok, seems the reason the returning `ASSIGNMENT_WORD` tokens is just because it's a specification of what kind of token is it (because the same structure would be a command argument, for example), so it should be processed in a next step but it says nothing about if that process should be done by the shell context or if it could be done by `bash-parser` itself, so I would do it there. The most `bash-parser` can do without ambiguities, the better.

**Comment by parro-it** [comment]
ASSIGNMENT_WORD token is identified by the [assignmentWord iterator] (https://github.com/vorpaljs/bash-parser/blob/master/src/tokenization-rules.js#L119). 

This iterator keep a flag `canBeCommandPrefix` that keep track if a token can form a `cmd_prefix` rule. A cmd_prefix rule could appear at the start of a line, after a `;` character or after a `|` character.

If a token is idefinied as a possible `cmd_prefix`, then I emit an ASSIGNMENT_WORD if the token contains the `=` character. This check should be improved, the spec says:

> [Assignment preceding command name]
> 
> [When the first word]
> 
> If the TOKEN does not contain the character '=', rule 1 is applied. Otherwise, 7b shall be applied.
> 
> [Not the first word]
> 
> If the TOKEN contains the <equals-sign> character:
> 
> If it begins with '=', the token WORD shall be returned.
> 
> If all the characters preceding '=' form a valid name (see XBD Name), the token ASSIGNMENT_WORD shall be returned. (Quoted characters cannot participate in forming a valid name.)
> 
> Otherwise, it is unspecified whether it is ASSIGNMENT_WORD or WORD that is returned.

We already exclude quoted words, but we should check that the part preceding the `=` is a valid name.
Once identified in the tokenizer, ASSIGNMENT_WORD are reduced by [this rule](https://github.com/vorpaljs/bash-parser/blob/master/src/grammar.jison#L219) in the grammar, that in turn form an AST node by calling [`prefix` method](https://github.com/vorpaljs/bash-parser/blob/master/src/ast-builder.js#L93) in ast-builder.js

**Comment by parro-it** [comment]
> The spec says that it should return the ASSIGNMENT_WORD token, but I think it should return a expanded AST node.

Do you means something like: 
```js
{
    type: 'assignment',
    target: 'var_name',
    source: '42'
}
```

Then I think it could be produced in ast-builder.js by adding a specific method to handle ASSIGNMENT_WORD tokens in the grammar.

**Comment by piranna** [comment]
> that in turn form an AST node by calling prefix method in ast-builder.js

So it's here where I think they should be processed and instead of returning a `cmd_prefix` token, go the extra mile and return a variable assigment AST node. We have already identified as a `ASSIGMENT_WORD`, why going back and return a generic `cmd_prefix` instead?

> Do you means something like:
> 
> {
>     type: 'assignment',
>     target: 'var_name',
>     source: '42'
> }
> 
> Then I think it could be produced in ast-builder.js by adding a specific method to handle ASSIGNMENT_WORD tokens in the grammar.

Yes, that's it. Type itself could be `ASSIGNMENT_WORD`, to make sure where this comes from, at the end it's just an identifier...

**Comment by piranna** [comment]
> source: '42'

I'm not sure if we should try to convert it to a `Number` object instead of use it as a string...

**Comment by parro-it** [comment]
> So it's here where I think they should be processed and instead of returning a cmd_prefix token, go the extra mile and return a variable assigment AST node. We have already identified as a ASSIGMENT_WORD, why going back and return a generic cmd_prefix instead?

There is not particular reason. But a `cmd_prefix` rule can be either an `io_redirect` rule or a ASSIGMENT_WORD token. Since an `io_redirect` has a defined structure:

```
{
   type: 'io_redirect',
  op: '>',
  file: 'file.txt'
}
```

I think at first that would be fine to identify ASSIGNMENT_WORD as simple strings.
But now I agree with you, it would be better to define a node for them, and also make the additional parsing and provide a target and source property.

> I'm not sure if we should try to convert it to a Number object instead of use it as a string...

I don't see for what could be useful, you have to treat it as a string anyway for any possible use case I can think of...

**Comment by piranna** [comment]
> I don't see for what could be useful, you have to treat it as a string anyway for any possible use case I can think of...

Make it easier to the user :-) At the end, if it's being used as a string it will be converted automatically...

**Comment by parro-it** [comment]
> Make it easier to the user :-)

Why it should be easier? Please provide a possbile use case of it as Number, otherwise it is a needless conversion...

**Comment by piranna** [comment]
> Why it should be easier? Please provide a possbile use case of it as Number, otherwise it is a needless conversion...

Arithmetic operations. You only see strings, but Bash internally convert them to numbers if it see it's possible, we should do it too.

**Comment by parro-it** [comment]
Ok, I think we could further discuss the argument when we'll implement arithmetic expansion.
In this example 

```bash
# repeat a command 100 times
x=100
while [ $x -gt 0 ]
do
    command    x=$(($x-1))
done
```

It could be effectvely useful to see 100 as number from its firts appearence on line 2.

**Comment by piranna** [comment]
:+1:

**Comment by parro-it** [comment]
Discussion continue on typed variable continue on #24
