### ISSUE TITLE
Book chapter - Architecture of Open Source Applications: The Bourne-Again Shell

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#23]
I found an useful chapter that describe the architecture of `bash` in the book `Architecture of Open Source Applications`. Is really interesting: http://aosabook.org/en/bash.html

This diagram clearly explain the recursivity of expansions I was talking about in other isse here:

![image](https://cloud.githubusercontent.com/assets/11197111/17187679/93dad81a-543a-11e6-8937-86c0263b9ed3.png)

**Comment by nfischer** [comment]
Where does glob expansion lie? That should be different than both brace expansion and tilde expansion.

**Comment by parro-it** [comment]
I'm not sure, maybe it lie in the "Filename Generation" block?

**Comment by nfischer** [comment]
Hmmm, could be. Just make sure that variables containing special characters in their value don't get globbed:

```bash
$ foo="file*.txt"
$ touch file1.txt
$ rm $foo # the "*" in "file*.txt" shouldn't get expanded
rm: cannot remove 'file*.txt': No such file or directory
```

**Comment by piranna** [comment]
> This diagram clearly explain the recursivity of expansions I was talking
about in other isse here:

As I told you the other day, that's needed to build a fully working
interpreter, but that's not needed to build a parser, so it should be an
optional step executed if the shell app gives it a callback to allow to do
the recursive expansion. Anyway good link and diagram ;-)

**Comment by AljoschaMeyer** [comment]
Just to confirm, 'word splitting' refers to glob expansion. Each block in the expansion sequence of the diagram corresponds to a subsection of [section 3.5 in the bash manual](https://www.gnu.org/software/bash/manual/bash.pdf#27), and the last one deals with glob expansion.

**Comment by parro-it** [comment]
> As I told you the other day, that's needed to build a fully working
interpreter, but that's not needed to build a parser, so it should be an
optional step executed if the shell app gives it a callback to allow to do
the recursive expansion. Anyway good link and diagram ;-)

Hi @piranna, it was not my intention to return on that discussion, I'm fine with what we decided to do. 👍  😄 

@AljoschaMeyer Thank you for the reference, I'll read the chapter later today.

**Comment by nfischer** [comment]
> Just to confirm, 'word splitting' refers to glob expansion.

@AljoschaMeyer :+1:

**Comment by AljoschaMeyer** [comment]
Ok, I meant to write 'filename generation', but somehow wrote 'word splitting' instead... Sorry about that.
