### ISSUE TITLE
Arithmetic expansion

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#24]
Continue discussion from #20 and from #16

**Comment by parro-it** [comment]
The arithmetic expression shall be processed according to the rules given in [Arithmetic Precision and Operations](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap01.html#tag_17_01_02_01)

**Comment by piranna** [comment]
This seems to be a DSL (Domain Specific Language) on it's own, so I think it should be implemented on its own module (project?) just for clarity.

**Comment by parro-it** [comment]
Since the rules for Arithmetic expansion are almost the same of C language, it could be useul to investigate if some javascript parser for C already exists, and use that.

**Comment by piranna** [comment]
Interesting... probably yes, thanks to Emscripten and Cheerp projects :-)

**Comment by parro-it** [comment]
Done. Since the semantic of the arithmetic part is the same of javascript, I finally used [babylon parser](https://github.com/babel/babylon) to parse it.
