### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#3]
I noticed test source code have incoherent source style. Some time use ', some time " and stuff like that.
I think could be useful to standardize that and setup a style linter. 
@dthree any preference for the tool? Maybe XO?

**Comment by dthree** [comment]
I prefer XO personally. That would be great.

**Comment by parro-it** [comment]
:+1: I will setup XO after I moved sources.

**Comment by parro-it** [comment]
Setup of XO is almost completed!
There still some errors due to undefined vars I need to investigate...
