### ISSUE TITLE
Quote removal should be handled in a special way in assignments.

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#30]
```bash
PS1=">"
```

is actually parsed as:

```json
{
  "type": "complete_command",
  "commands": [
    {
      "type": "simple_command",
      "name": {
        "text": "",
        "type": "word"
      },
      "prefix": [
        {
          "text": "PS1=\">",
          "type": "assignment_word"
        }
      ]
    }
  ]
}
```

because quote removal is removing quotes only at start and at end of word nodes

**Comment by parro-it** [comment]
I solved this, now quote removal happens for each non escaped quote in word and assignment_word.
The previous example is now parsed as `"text": "PS1=>"`

**Comment by nfischer** [comment]
@parro-it looks like quote removal (*for single quotes*) doesn't quite work right still, here's an example:

```sh
echo foo"bar"'baz'
```

I see it parsed as:

```js
      "suffix": [
        {
          "text": "foobar'baz'", // extra single quotes here
          "type": "word"
        }
      ]
```

It should instead be parsed as:

```js
      "suffix": [
        {
          "text": "foobarbaz", // no single quotes here
          "type": "word"
        }
      ]
```

Please correct me if I'm missing something. This is going off the most recent version on the live site.

**Comment by parro-it** [comment]
@nfisher you're right, there still something wrong, I will try to investigate tomorrow...

**Comment by nfischer** [comment]
Actually, I see some more bugs with the parsing. For example, this does not throw an error:

```sh
echo hello world's # this single quote should require a closing single quote
echo foo "bar # this double quote also requires a closing quote
```

**Comment by parro-it** [comment]
Ok, both issues should be solved now. We are now handling quote removal using code extracted from shell-quote https://github.com/vorpaljs/bash-parser/tree/master/packages/shell-quote-word
