### ISSUE TITLE
Line continuation with empty lines doesn't work properly

### ISSUE THREAD

**Issue by nfischer** [vorpaljs/bash-parser#33]
Example shell code:

```sh
echo \
hi \
\
there
```

This should be exactly equivalent to:

```sh
echo hi there
```

But I'm seeing it keep an extra backslash in the AST node:

```js
        {
          "text": "\\there",
          "type": "word"
        }
```

**Comment by parro-it** [comment]
This is partially solved, your example now is parsed correctly.
However, this other one doesn't:

```bash
echo \
hi \

echo hi
```

This result in an AST with first echo command having two arguments, of which the second is empty.

**Comment by parro-it** [comment]
Latest commits also solves the problem above, closing this...
