### ISSUE TITLE
Non POSIX extensions

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#35]
I found an interesting document on GNU site:
https://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html

It describe all the bash feature disabled when you using the --posix command-line option.
I will extract from there all the feature we need to add to the parser to fully support non-standard bash features.

It would be nice to find something similar for zsh too

**Comment by piranna** [comment]
I would add them as optional extensions, don't know if enabled by a flag or
with a plugins mechanism (that would be just an array of extension objects
on the parser constructor) or something similar, just for clarity and to
clearly follow the standard specs.

**Comment by parro-it** [comment]
Having a plugin system would be great! 

It should be easy to implement one on the lexer level. It is implemented as a composition of a list of functions, each one accepting an iterable of tokens and returning another one, so we can allow to add others or remove existing ones.

Also, we could allow to apply custom visitors on the generated AST, similar to what babel does.

However, bash specific features imply changes in the jison grammar, and I have no idea how to customize that, so for now I would go with a flag... maybe a `mode` flag, accepting 'posix', 'bash' & 'zsh' as values.

**Comment by piranna** [comment]
> Also, we could allow to apply custom visitors on the generated AST,
similar to what babel does.

Would this allow to expand the syntax with custom features, for example
define and call Javascript functions directly and not only shell ones?

> However, bash specific features imply changes in the jison grammar, and I
have no idea how to customize that, so for now I would go with a flag...
maybe a mode flag, accepting 'posix', 'bash' & 'zsh' as values.

Maybe that parts of the grammar would be overwritten when a plugin is
loaded? Problem would be how to have several plugins loaded at the same
time... :-/

**Comment by parro-it** [comment]
> Would this allow to expand the syntax with custom features, for example
define and call Javascript functions directly and not only shell ones?

What is executed at runtime to run a command node is entirely up to the caller: you can run a process or call a js function. Definition is more problematic: the grammar does not directly accept javascript code, but one can always intercept e.g. heredoc block nodes (actually unimplemented) in a visitor and parse the content with parsers for any language

> Maybe that parts of the grammar would be overwritten when a plugin is
loaded? Problem would be how to have several plugins loaded at the same
time... :-/

I was thinking the same... However, this would involve shipping jison as a dependency to recompile the grammar each time. And the jison compilation is slow, we should maybe cache the results and only recompile when used plugins changes somehow.

But the real problem Is the one you said: if two plugin replace the same rule, there is a conflict. We should check how babylon parser handle syntax extensions

**Comment by piranna** [comment]
>> Would this allow to expand the syntax with custom features, for example
>> define and call Javascript functions directly and not only shell ones?
>
> What is executed at runtime to run a command node is entirely up to the
caller: you can run a process or call a js function. Definition is more
problematic: the grammar does not directly accept javascript code, but one
can always intercept e.g. heredoc block nodes (actually unimplemented) in a
visitor and parse the content with parsers for any language

I was talking about being able to extend the grammar and allow to define
Javascript functions directly, not as a DSL.

>> Maybe that parts of the grammar would be overwritten when a plugin is
>> loaded? Problem would be how to have several plugins loaded at the same
>> time... :-/
>
> I was thinking the same... However, this would involve shipping jison as
a dependency to recompile the grammar each time. And the jison compilation
is slow, we should maybe cache the results and only recompile when used
plugins changes somehow.

Not really, it's not needed to distribute the grammar but instead the
already compiled Javascript code.

> But the real problem Is the one you said: if two plugin replace the same
rule, there is a conflict. We should check how babylon parser handle syntax
extensions

The most simple option would be to stack them, getting priority the latest
one. What about implementing a rsh / reduce shell? This could allow to
easily test the plugin mechanism before adding the bash functionality...

**Comment by parro-it** [comment]
> I was talking about being able to extend the grammar and allow to define
Javascript functions directly, not as a DSL.

I don't think the entire javascript grammar could fit inside the shell one without a way to disambiguate the two. For example:

```js
echo (42);
```

This could be either a call to a js function `echo` passing 42 as argument, or a call to the shell command `echo` passing the output of a shell substitution running the command `42`. 
You need a way to disambiguate between the two.

> Not really, it's not needed to distribute the grammar but instead the
already compiled Javascript code.

This completely defeat the advantages of having multiple plugins: you can almost use one at a time.
Moreover If we'll use this method to implement different shell syntaxes, we'll have to maintain multiple versions of the grammar.

> What about implementing a rsh / reduce shell? This could allow to
easily test the plugin mechanism before adding the bash functionality...

What is exactly an rsh / reduce shell? The [Unix remote shell](https://en.wikipedia.org/wiki/Remote_Shell)?

**Comment by nfischer** [comment]
I'm glad to see the project moving along! This is awesome work! :smile: I just thought I'd chime in with my thoughts on this thread:

---

> I don't think the entire javascript grammar could fit inside the shell one without a way to disambiguate the two. For example:
> echo (42);

Forgive me if I'm misinterpreting, but I don't think he was talking about creating a bash/JS hybrid, but was talking about using javascript to define what to do when facing a particular bash syntax. So the syntax is still bash, but we might allow plugin authors to provide custom functions for how to parse certain things.

I agree, it would be too difficult to disambiguate between bash and JS syntax all the time.

---

> This completely defeat the advantages of having multiple plugins: you can almost use one at a time.
Moreover If we'll use this method to implement different shell syntaxes, we'll have to maintain multiple versions of the grammar.

Why would you want to use more than one at a time? It would be weird to parse half a file as `sh` and the other have as `zsh`.

I don't think using one at a time is an issue. The issue is one of maintenance. If we have 3 different modes, it really means 3 different grammars (with considerable overlap). For what it's worth, I think writing multiple grammars *is* the way to go, but only if we can create a good way to treat POSIX `sh` as a "super grammar" for `bash` and `zsh`. I know ohm supports extending grammars, but I'm sure jison must support that as well.

I think the "modes" approach is going to be easier than designing a full plugin architecture, and I don't see much benefit to doing plugins. If we stick to modes, then all the shell grammars are conveniently wrapped under one npm module, we don't have to devote effort to externalizing our APIs, and we won't have to divide work across multiple repos (which makes refactors a nightmare). The advantage to plugins is that outside contributors could write their own plugins, but realistically they could just submit a pull request here if they were interested, and then we all benefit.

---

> What about implementing a rsh / reduce shell? This could allow to
> easily test the plugin mechanism before adding the bash functionality...

Why not just start by adding in bash-isms? POSIX sh is a strict subset of Bash, if I recall correctly, so we've already almost got our real "reduced shell."

I think the easiest place to start is with [string manipulation](http://tldp.org/LDP/abs/html/string-manipulation.html), since it just modifies the rule for variable references. I think it'll be a simple enough starting point, and I've [already implemented](https://github.com/nfischer/shelljs-transpiler/issues/4) some of them for my PEG.

**Comment by parro-it** [comment]
> Why would you want to use more than one at a time? It would be weird to parse half a file as sh and the other have as zsh.

I was thinking about small plugins, that just change some rules in the grammar, but effectively it does not make sense: if one would write a new "mode" plugin, it almost surely is because it want to support a new  shell flavor, so it would be ok to replace the entire grammar.

> Why not just start by adding in bash-isms? POSIX sh is a strict subset of Bash, if I recall correctly, so we've already almost got our real "reduced shell."

I agree with you: the primary purpose of this project is, after all, to serve as a grammar for `cash`, that will support bash syntax....

Regarding the implementation, jison support two format for the grammar: the classic ebnf format I'm using and a JSON format. 

We could convert the actual grammar to JSON, and then each mode will have another JSON partial grammar conaining onyl the rules to overwrite.

A build tool will take care of load the POSIX grammar, overwrite it with the mode grammar, and then compile the results with jison to produce the actual grammar.

Moreover, each mode will specify:

* a list of tokenization rule to apply in `src/posix-shell-lexer.js`, eventually replacing the POSIX ones he need to override

* an object to replace the POSIX ast builder in `src/ast-builder.js`, that could use the existing one and replace or add methods where there is need.

This should be flexible enough to completely rewrite the POSIX parser if one need to.

**Comment by piranna** [comment]
>> I was talking about being able to extend the grammar and allow to define
>> Javascript functions directly, not as a DSL.
>
> I don't think the entire javascript grammar could fit inside the shell
one without a way to disambiguate the two. For example:
>
> echo (42);
>
> This could be either a call to a js function echo passing 42 as argument,
or a call to the shell command echo passing the output of a shell
substitution running the command 42.
> You need a way to disambiguate between the two.

:-/

>> Not really, it's not needed to distribute the grammar but instead the
>> already compiled Javascript code.
>
> This completely defeat the advantages of having multiple plugins: you can
almost use one at a time.
> Moreover If we'll use this method to implement different shell syntaxes,
we'll have to maintain multiple versions of the grammar.

Not really, I was thinking about partial grammars that hook on particular
places, not generate the full grammars...

>> What about implementing a rsh / reduce shell? This could allow to
>> easily test the plugin mechanism before adding the bash functionality...
>
> What is exactly an rsh / reduce shell? The Unix remote shell?

No, the restricted shell https://en.m.wikipedia.org/wiki/Restricted_shell,
but seems to ve more like at shell level than parser except maybe for the
variables asignation, so it doesn't makes sense. But, if you see it easy to
remove variables asignation from the grammar, it could be a good example of
how to implement the plugins... :-)

**Comment by piranna** [comment]
> A build tool will take care of load the POSIX grammar, overwrite it with
the mode grammar, and then compile the results with jison to produce the
actual grammar.

This totally makes sense.

**Comment by parro-it** [comment]
I started to implement modes plugins in the `modes` branch. I wrote some [documentation on the design](https://github.com/vorpaljs/bash-parser/blob/modes/documents/mode.md), I hope that it make sense...

The `posix` mode is [in this folder](https://github.com/vorpaljs/bash-parser/tree/modes/src/modes/posix) and the `bash` one is [here](https://github.com/vorpaljs/bash-parser/tree/modes/src/modes/bash).

By now, the only difference in the `bash` mode is that it apply alias substitution on reserved words.

**Comment by parro-it** [comment]
The branch is now merged into master. I also rewrote the tokenizer from scratch, using a state machine.
I think the tokenizer code is better desgined now and has a greater maintainability...
