### ISSUE TITLE
Compound list shall accept redirection

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#40]
e.g. :

````bash
{echo 1;echo 2; echo 3} > results.txt
```

the redirection part is completely ignored

**Comment by AljoschaMeyer** [comment]
Tried to run that snippet (`{echo 1;echo 2; echo 3} > results.txt`) and got:

```
bash: {echo: command not found
2
```
`cat results.txt` prints `3}`

So bash doesn't think to seem this is valid either. Bash version: 4.3.046-1

**Comment by piranna** [comment]
Not sure if it's a bash bug, or we're too much used to languajes with a
solid grammar... I know bash and shell use whitespace as separators, but
also for control flow structures?

I would open an issue or ask on the bash mail-list...

**Comment by piranna** [comment]
https://www.gnu.org/software/bash/
help-bash@gnu.org

Here is the address.

**Comment by parro-it** [comment]
It work using a space after the opening brace, and writing a semicolon after each statement:

```bash
{ echo 1;echo 2; echo 3;} > results.txt
```

So, we still need to parse redirections, but #39 is a false problem, I'll close that,
@AljoschaMeyer thank you for the investigation!
