### ISSUE TITLE
regenerate AST into bash command

### ISSUE THREAD

**Issue by gabrielcsapo** [vorpaljs/bash-parser#47]
Hello! I really appreciate all the work you did on this module!

I am looking for functionality to turn an AST back into a bash script.

```
{
  "type": "Script",
  "commands": [
    {
      "type": "Command",
      "name": {
        "text": "echo",
        "type": "Word"
      },
      "suffix": [
        {
          "text": "hello",
          "type": "Word"
        },
        {
          "text": "world",
          "type": "Word"
        }
      ]
    }
  ]
}
```

would turn into `echo hello world`

Would that be possible or a feature that you would want to be added?

**Comment by parro-it** [comment]
> Hello! I really appreciate all the work you did on this module!

:smile: thank you, I'm happy to hear that!

> Would that be possible or a feature that you would want to be added?

It is a feature I was thinking to implement myself in the future, it would be beautiful if you could wrote a module to do that, if you do mind...

There is some visitor machinery implemented in [bash-ast-traverser package](https://github.com/vorpaljs/bash-parser/tree/master/packages/bash-ast-traverser). 

This module help you register visitors that can alter AST node objects. 
You could wrote a visitor that add a recursive `generateSource` method to every AST node.

For your basic example to work, you should wrote a visistor such this:

```js
// pseudocode!
{
Word: node => Object.assign({}, node, {
    sourceCode: () node.text
}),

Command: ({name, suffix}) => Object.assign({}, node, {
    sourceCode: () => name.sourceCode() + suffix.map(s => s.sourceCode()).join(' ')
})

}
```

**Comment by gabrielcsapo** [comment]
@parro-it yeah I noticed the BASH traverser package, will see if I can get something working and if it works out I could open a PR to this repo?

**Comment by parro-it** [comment]
Writing that stuff for every AST type node would be a lot of work... anyway, this should work fine.

However, if you have to generate source code that is formatted exactly as the original one, this is difficult to implement. The AST code contains line and column info for every node, but final token are not saved, so for example:

```bash
function example (a, b) 
{
    echo bar;
}
```

the AST for this code does not contains information about the position of `function`, `{`, `}` tokens, so you cannot restore them at the saem source position.

Also, comments are not actuallt inserted in the AST.

**Comment by parro-it** [comment]
> @parro-it yeah I noticed the BASH traverser package, will see if I can get something working and if it works out I could open a PR to this repo?

Yeah that would be beautiful !

**Comment by parro-it** [comment]
> @parro-it yeah I noticed the BASH traverser package, will see if I can get something working and if it works out I could open a PR to this repo?
> Yeah that would be beautiful !

You could make a new package under `packages` directory

**Comment by piranna** [comment]
You could wrote a visitor that add a recursive generateSource method to
every AST node.

Better name it toSource(), as Firefox does, or if you want to be fully
compliant toString(), but that would interfiere with the representation of
the json objects of the AST itself... Maybe toBash()? :-)

**Comment by piranna** [comment]
the AST for this code does not contains information about the position
of function, {, } tokens, so you cannot restore them at the saem
source position.

Also, comments are not actuallt inserted in the AST.

Could they be stored in the AST too? Nodes can be ignored later...

**Comment by parro-it** [comment]
> Better name it toSource(), as Firefox does
:+1: I like this!

> Could they be stored in the AST too? Nodes can be ignored later...

Yes, I thought of add a set of bare tokens property to the AST nodes, for examples,
`Function` will have `OpenBraceToken`, `FunctionToken`, `CloseBraceToken` etc.
These properties will consist only of source code position info.

**Comment by gabrielcsapo** [comment]
Yeah I don't think the source location matters as much, especially since bash is pretty flexible. I am working on getting a simple AST to code example working in https://github.com/gabrielcsapo/shell-p. Will get back when I have working code!

**Comment by gabrielcsapo** [comment]
@parro-it have you thought of producing an output that resembles something like https://github.com/ternjs/acorn?

**Comment by gabrielcsapo** [comment]
okay so I have something working! https://github.com/gabrielcsapo/shell-p/blob/master/index.js#L7, it not complete, I need some eyes on examples that we can catch more edge cases, if you want to start a discussion there we can migrate the code when it is done to this repo as a complete AST parse and generator. @parro-it @piranna what do you think?

**Comment by piranna** [comment]
If you have it working on an external independent module, I would left it
as is.

**Comment by gabrielcsapo** [comment]
Well shell-p's main purpose is not to parse and render a shell script into AST and back, it is much more a biproduct of that

**Comment by parro-it** [comment]
Great job @gabrielcsapo , I'll leave some comments there...

**Comment by gabrielcsapo** [comment]
@parro-it just saw this, where would you want to move it to? A sub npm module? Would is the status of getting function parsing and such working?

**Comment by parro-it** [comment]
@gabrielcsapo, I think a repo under vorpaljs organization would be the best choice... 
You'll have to wait for @dthree to give us permission to create repo under the org

**Comment by gabrielcsapo** [comment]
Woot woot should I create a repo and transfer ownership? Or should I wait for one to be made @parro-it I really want this to be a thing. I am working on https://github.com/gabrielcsapo/shell-p for some stuff for work but can't use it until I get more of the bash syntax supported like functions and subprocess, so anything I can do to help I will 😊

**Comment by piranna** [comment]
@gabrielcsapo I would do a fork on the organization, use git branch to remove content, and later `git push -f` to upload just the folder to the repo. You have more info at https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by parro-it** [comment]
@gabrielcsapo @dthree just give me permission to create repos under vorpaljs organization, so I think the simplest think is that I create the new repo here and make you a member.

What's about the name?
`escodegen` generate ES code, so what about `bash-codegen`?

**Comment by piranna** [comment]
You can do the repo on your profile, and later transfer it to the vorpaljs organization when you get permissions, this way we can be going moving this forward :-)

**Comment by parro-it** [comment]
> You can do the repo on your profile, and later transfer it to the vorpaljs organization when you get permissions, this way we can be going moving this forward :-)

I already have permissions... sorry for my english, I make lot of mistakes...

**Comment by piranna** [comment]
Don't worry :-)

**Comment by parro-it** [comment]
So, I go on and create `bash-codegen`, we could eventually rename it if needed.
@gabrielcsapo I made you a member, you should receive an invitation...

**Comment by parro-it** [comment]
@gabrielcsapo the repo is available on https://github.com/vorpaljs/bash-codegen let me know if you have problems accessing

**Comment by gabrielcsapo** [comment]
@parro-it I am not able to fork or update bash-codegen ☹️

**Comment by nfischer** [comment]
@gabrielcsapo there's no code there, so I don't think you can fork it. I think @parro-it intends for you to `git push` your local work.

**Comment by gabrielcsapo** [comment]
@nfischer I would but I don't have permissions to push to it 🙈That is what I meant by update

**Comment by parro-it** [comment]
@gabrielcsapo seems you didn't accept the invite:

![image](https://user-images.githubusercontent.com/11197111/27506946-0dedb1b0-58c5-11e7-82d3-3d0098b48cf1.png)

You should have admin access to the repo after you accept.
