### ISSUE TITLE
Move out `packages` folder

### ISSUE THREAD

**Issue by piranna** [vorpaljs/bash-parser#48]
Shouldn't `packages` folder items being their own projects? One first step would be to rename it to `node_modules` and define them as `bundledDependencies`...

**Comment by parro-it** [comment]
> Shouldn't packages folder items being their own projects?

Yes they should, lerna complicates things...

> One first step would be to rename it to node_modules and define them as bundledDependencies...

Not sure what you mean here: they are already published to npm, why bundle them?

**Comment by piranna** [comment]
> Not sure what you mean here: they are already published to npm, why bundle them?

Are they already published as independent modules on npm? Then I would delete the `packages` folder altogheter and use them as dependencies instead.

**Comment by parro-it** [comment]
They are already used as npm dependencies... but we need to move them to their own git repos.
I', not sure if we can create new repos under vorpaljs org. 

@dthree what do you think about?

**Comment by gabrielcsapo** [comment]
I think this would be best, it would help make things less complicated with lerna.

**Comment by parro-it** [comment]
I noticed I have no right to create new repos on vorpaljs org. @dthree could you help me?

**Comment by dthree** [comment]
Done :)

**Comment by parro-it** [comment]
Thank you 
👻

**Comment by parro-it** [comment]
I moved all packages to their own repos:

* https://github.com/vorpaljs/shell-runtime
* https://github.com/vorpaljs/bash-parser-playground
* https://github.com/vorpaljs/bash-ast-traverser
* https://github.com/vorpaljs/mode-grammar-builder
* https://github.com/vorpaljs/bash-codegen

Every repo now has CI on travis passing and a new (almost unchanged) version published on npm

**Comment by piranna** [comment]
Great! :-D

**Comment by gabrielcsapo** [comment]
@parro-it you rock!
