### ISSUE TITLE
Add reference to shell-parse

### ISSUE THREAD

**Issue by piranna** [vorpaljs/bash-parser#5]
We should add a reference to shell-parse project at least as tribute for being the basis of this project and/or try to merge our change upstream. If not, we should think about publish our change on npm, there are some of the improvements here that I was willingly to add to nsh...

**Comment by parro-it** [comment]
I agree. But before, we have to better setup the repo: I didn't change package.json file, it still has original repo path and name.

**Comment by dthree** [comment]
:+1:

Sorry I've been so quiet guys. Have had zero time for OSS recently. Hoping that changes soon. Don't think I've abandoned you!

**Comment by parro-it** [comment]
Added in "related projects" section
