### ISSUE TITLE
Cannot parse EXTENDED_GLOB

### ISSUE THREAD

**Issue by denysdovhan** [vorpaljs/bash-parser#55]
The same issue is present in [shellcheck](https://github.com/koalaman/shellcheck/issues/855).

See: https://github.com/koalaman/shellcheck/issues/855

**Comment by parro-it** [comment]
We doesn't support zsh, and there isn't any plan to add support for it ATM, sorry.

**Comment by denysdovhan** [comment]
Are you open to possible PRs with fixes?

Can you, at least guide where I can fix that issue?

**Comment by parro-it** [comment]
No, sorry, it's not  a simple fix, we just don't support zsh, only bash and posix sh.
