### ISSUE TITLE
Missing support function keyword / declarations

### ISSUE THREAD

**Issue by inbre001** [vorpaljs/bash-parser#56]
These 2 Types of function declarations do not seem to work.

```bash
function F2 {
	echo "function F2"
}

function F3() {
	echo "function F3()"
}
```

> Shell Function Definitions
>        A shell function is an object that is called like a simple command and executes a compound command with a new set of positional parameters.  Shell functions are declared as follows:
> 
>        name () compound-command [redirection]
>        function name [()] compound-command [redirection]
>               This defines a function named name.  The reserved word function is optional.  If the function reserved word is supplied, the parentheses are optional.  The body of the function is the compound command  compound-command
>               (see  Compound  Commands  above).  That command is usually a list of commands between { and }, but may be any command listed under Compound Commands above, with one exception: If the function reserved word is used, but
>               the parentheses are not supplied, the braces are required.  compound-command is executed whenever name is specified as the name of a simple command.  When in posix mode, name may not be the name of  one  of  the  POSIX
>               special  builtins.   Any  redirections  (see  REDIRECTION below) specified when a function is defined are performed when the function is executed.  The exit status of a function definition is zero unless a syntax error
>               occurs or a readonly function with the same name already exists.  When executed, the exit status of a function is the exit status of the last command executed in the body.  (See FUNCTIONS below.)
>

**Comment by parro-it** [comment]
The `function` keyword is not POSIX. See #37 for a list of bash feature to implement.
Would you mind to write a PR? I don't have the time ATM to work on this for myself...
