### ISSUE TITLE
Redirect should be allowed immediately following argument

### ISSUE THREAD

**Issue by nfischer** [vorpaljs/bash-parser#7]
Commands like `echo foo > file.txt` should be exactly identical to `echo foo>file.txt`. Whitespace does not matter around the redirect operators in this case.

Also, this should be the same as `echo>file.txt foo`. `echo > file.txt foo` works right now, but this might be an edge case worth checking as well once this is implemented.

**Comment by parro-it** [comment]
Fixed in new branch. See [test](https://github.com/vorpaljs/bash-parser/blob/master/test/test-regressions.js#L5)
