### ISSUE TITLE
Fix rule for variables

### ISSUE THREAD

**Issue by nfischer** [vorpaljs/bash-parser#9]
I noticed that `echo $1bar` says that its argument is a variable named `1bar`, which isn't correct behavior in either sh or bash.

Variables should start with a letter or \_ and should contain only letters, digits, and \_. References to arguments can be (correct me if I'm wrong) any number of digits. So you can't have a variable that starts with a digit and is followed by any non-digits.

Expected behavior: `echo $1bar` should concatenate `$1`'s value with "bar". `echo ${1bar}` should give a bad substitution.

**Comment by piranna** [comment]
Just a matter of update the regexp.

**Comment by nfischer** [comment]
Yeah, figured this would be pretty easy. I'll take this on in the next few days if no one else does.

**Comment by parro-it** [comment]
This is now fixed and checkded by [this test](https://github.com/vorpaljs/bash-parser/blob/master/test/test-positional-parameter.js#L5)

**Comment by piranna** [comment]
Great! :-D
